config/routes.rb
Rails.application.routes.draw do

  get 'about' => "pages#about"
  get 'contact' => "pages#contact"
  get 'equipe' => "pages#team", as: :team
  get 'search' => "pages#search"
  post 'search' => "pages#search"
  get "search/:category" => "pages#search"

  root 'pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  @restaurants = %w(serre bristrol dindon)

  @search = params[:search_meal]
    @name = "Botica"
    @menu = %w(bitoque salmon codfish)

    @menu.select! {|meal| meal == @search}

  end

  def contact
  end

  def team
  end

  def search
    @category = params[:category]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lacuillere</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1> La cuillere </h1>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>welcome</h1>

<% name = "boris" %>

<h2> Salut <%= name.capitalize %> </h2>

<p>We are <%= Time.now.strftime("%d/%m/%Y") %></p>


<% @restaurants.each do |restaurant| %>

<%= restaurant %>

<% end %>


<%= link_to "Cherchez un restaurant", search_path %>
<%= link_to"meet l'équipe", team_path %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/search.html.erb
<h1>Cherchez un resto</h1>

<form action="/search" method="post" >
  <input type="text" name="search[category]" placeholder="category">
  <input type="text" name="search[name]" placeholder="name">
  <input type="submit" value="search">
</form>
<br>

app/views/pages/team.html.erb
<h2>This is a team </h2>